accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import logout

from accounts.views import send_login_email, login

urlpatterns = [
    url(r"send_login_email$", send_login_email, name="send_login_email"),
    url(r"^login", login, name="login"),
    url(r"^logout", logout, {"next_page": "/"}, name="logout")
]

lists/urls.py
from django.conf.urls import url
from lists.views import view_list, new_list, my_lists, share_list

urlpatterns = [
    url(r"new$", new_list, name="new_list"),
    url(r"(\d+)/$", view_list, name="view_list"),
    url(r"users/(.+)/$", my_lists, name="my_lists"),
    url(r"(\d+)/share$", share_list, name="share_list"),
]

superlists/urls.py
from django.conf.urls import url, include
from lists.views import home_page
from lists import urls as list_urls
from accounts import urls as account_urls

urlpatterns = [
    url(r"^$", home_page, name="home"),
    url(r"^lists/", include(list_urls)),
    url(r"^accounts/", include(account_urls)),
]

accounts/models.py
from uuid import uuid4
from django.db import models
from django.contrib import auth
# Create your models here.
from django.db.models import EmailField, CharField
auth.signals.user_logged_in.disconnect(auth.models.update_last_login)


class User(models.Model):
    email = EmailField(unique=True, primary_key=True)

    REQUIRED_FIELDS = []
    USERNAME_FIELD = 'email'
    is_anonymous = False
    is_authenticated = True


class Token(models.Model):
    email = EmailField()
    uid = CharField(default=uuid4, max_length=40)

lists/models.py
from django.conf import settings
from django.db import models
from django.db.models import ManyToManyField
from django.urls import reverse

from accounts.models import User


class List(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True)
    shared_with = ManyToManyField(User, "sharedlists")

    def get_absolute_url(self):
        return reverse('view_list', args=[self.id])

    @staticmethod
    def create_new(first_task_text, owner=None):
        task_list = List.objects.create(owner=owner)
        Task.objects.create(text=first_task_text, list=task_list)
        return task_list

    @property
    def name(self):
        return self.task_set.first().text


class Task(models.Model):
    class Meta:
        ordering = ('id',)
        unique_together = ('list', 'text')

    text = models.TextField(default="")
    list = models.ForeignKey(List, default=None)

    def __str__(self):
        return self.text

lists/forms.py
from django.core.exceptions import ValidationError
from django.forms import TextInput, ModelForm

from lists.models import Task, List

EMPTY_TASK_ERROR = 'Cannot add an empty task'
DUPLICATING_TASK_ERROR = 'Cannot add a duplicating task'


class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ('text',)
        widgets = {
            'text': TextInput({
                'placeholder': 'Enter a task',
                'class': 'form-control input-lg'
            })
        }
        error_messages = {
            'text': {
                'required': EMPTY_TASK_ERROR
            }
        }


class NewListTaskForm(TaskForm):
    def save(self, owner):
        if owner.is_authenticated:
            return List.create_new(first_task_text=self.cleaned_data["text"], owner=owner)
        else:
            return List.create_new(first_task_text=self.cleaned_data["text"])


class ExistingListTaskForm(TaskForm):
    def __init__(self, for_list, *args, **kwargs):
        super(ExistingListTaskForm, self).__init__(*args, **kwargs)
        self.instance.list = for_list

    def validate_unique(self):
        try:
            self.instance.validate_unique()
        except ValidationError as e:
            e.error_dict = {'text': [DUPLICATING_TASK_ERROR]}
            self._update_errors(e)

accounts/views.py
from django.contrib import messages
from django.contrib import auth
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.urls import reverse
from accounts.models import Token


def send_login_email(request):
    email = request.POST["email"]
    token = Token.objects.create(email=email)
    login_link = request.build_absolute_uri(f'{reverse("login")}?token={token.uid}')
    send_mail("Your login link for TODO task list",
              f"Use this link to login: {login_link}", "testinggoat@mail.ru", [email])
    messages.success(request,
                     "Check your email for login link")
    return redirect("/")


def login(request):
    user = auth.authenticate(uid=request.GET.get("token"))
    if user:
        auth.login(request, user)
    return redirect("/")

lists/views.py
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.http import HttpRequest
from django.shortcuts import render, redirect

from lists.forms import TaskForm, ExistingListTaskForm, NewListTaskForm
from lists.models import Task, List


def home_page(request: HttpRequest):
    return render(request, "home.html", {"form": TaskForm()})


def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    form = ExistingListTaskForm(for_list=list_)
    if request.method == "POST":
        form = ExistingListTaskForm(for_list=list_, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(list_)
    return render(request, "list.html", {"list": list_,
                                         "form": form,
                                         })


def new_list(request):
    form = NewListTaskForm(data=request.POST)
    if form.is_valid():
        task_list = form.save(owner=request.user)
        return redirect(task_list)
    return render(request, "home.html", {"form": form})


User = get_user_model()


def my_lists(request, email):
    owner = User.objects.get(email=email)
    return render(request, "my_lists.html", {"owner": owner})


def share_list(request, list_id):
    task_list = List.objects.get(id=list_id)
    task_list.shared_with.add(request.POST["share"])
    return redirect(task_list)

lists/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Todo list</title>
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/base.css" rel="stylesheet">
    <link href='/static/font-awesome/css/font-awesome.min.css' rel="stylesheet" type="text/css">

</head>
<body>
<div class="container">

    <div class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
            <a href="/" class="navbar-brand">Uberlist</a>
            {% if user.email %}
                <ul class="nav navbar-nav navbar-left">
                    <li><a href={% url 'my_lists' user.email %}>My Task Lists</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="navbar-text">Logged in as {{ user.email }}</li>
                    <li><a href="{% url 'logout' %}">Logout</a></li>
                </ul>
            {% else %}
                <form class="navbar-form navbar-right" method="post" action="{% url 'send_login_email' %}">
                    <span>Enter email</span> <input class="form-control" name="email" type="text"/> {% csrf_token %}
                </form>
            {% endif %}
        </div>
    </div>

    {% if messages %}
        <div class="row">
            <div class="col-md-8">
                {% for message in messages %}
                    {% if message.level_tag == 'success' %}
                        <div class="alert alert-success">{{ message }}</div>
                    {% else %}
                        <div class="alert alert-warning">{{ message }}</div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    {% endif %}

    <div class="col-md-6 col-md-offset-3 jumbotron">
        <div class="text-center">
            <h1>{% block header_text %}{% endblock %}</h1>
            {% block task_form %}
                <form method="POST" action={% block form_action %}{% endblock %}>
                    {{ form.text }} {% csrf_token %}
                    {% if form.errors %}
                        <div class="form-group has-error">
                            <span class="help-block">{{ form.text.errors }}</span>
                        </div>
                    {% endif %}
                </form>
            {% endblock %}
        </div>
    </div>

    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            {% block table %}
            {% endblock %}
        </div>

        <div class="col-md-6 col-md-offset-3">
            {% block extra_content %}
            {% endblock %}
        </div>
    </div>

</div>

<script src="/static/jquery-3.5.0.min.js"></script>
<script src="/static/list.js"></script>
<script>
    $(document).ready(
        function () {
            window.Superlists.initialize();
        }
    )
</script>

</body>
</html>

lists/templates/home.html
{% extends 'base.html' %}

{% block header_text %}Add a new Todo list{% endblock %}

{% block form_action %}"{% url 'new_list' %}"{% endblock %}

lists/templates/list.html
{% extends 'base.html' %}

{% block header_text %}Your Todo list{% endblock %}

{% block form_action %}{% url 'view_list' list.id %}{% endblock %}

{% block table %}
    <h4>Owner: <span id="id_list_owner">{{ list.owner.email }}</span></h4>
    <table id="id_task_table" class="table">
        {% for task in list.task_set.all %}
            <tr>
                <td>{{ forloop.counter }}: {{ task.text }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}


{% block extra_content %}
    {% if user.email %}

        <div class="row">
            <div class="col-md-6">
                <h4>Shared with</h4>
                <ul>
                    {% for user in list.shared_with.all %}
                        <li class="list-share">{{ user.email }}</li>
                    {% endfor %}
                </ul>
            </div>
            <div class="col-md-6 text-center">
                <form method="post" action="{% url 'share_list' list.id %}">
                    <div class="form-group">
                        <h4>Share</h4>
                        <input class="form-control" name="share" type="text" placeholder="your-friend@example.com"/> {% csrf_token %}
                    </div>
                </form>
            </div>
        </div>
    {% endif %}
{% endblock %}

lists/templates/my_lists.html
{% extends 'base.html' %}

{% block header_text %}
    <div class="row">My Task Lists</div>{% endblock %}
{% block task_form %}{% endblock %}
{% block extra_content %}
{#    <div class="row">#}
        <h2>{{ owner.email }}'s tasks</h2>
        <ul>
            {% for task_list in owner.list_set.all %}
                <li><a href={{ task_list.get_absolute_url }}> {{ task_list.name }}</a></li>
            {% endfor %}

        </ul>

    <h2>Shared tasks</h2>
        <ul>
            {% for task_list in owner.sharedlists.all %}
                <li><a href={{ task_list.get_absolute_url }}>{{ task_list.name }}</a></li>
            {% endfor %}

        </ul>
{#    </div>#}

{% endblock %}